import { AcidDomain } from "./acid-domain.interface";
import { DAMAGE_DOMAIN } from "./damage-domain.interface";
import { DIRE_ORB_EXPLOSION } from "./dire-orb-explosion.interface";
import { DIRE_ORB_TELEFRAG } from "./dire-orb-telefrag.interface";
import { DIRE_ORB } from "./dire-orb.interface";
import { IFallDamage } from "./fall-damage.interface";
import { GAUNTLET } from "./gauntlet.interface";
import { KILL_DOMAIN } from "./kill-domain.interface";
import { LAGBOLT } from "./lagbolt.interface";
import { LIGHTNING_GUN } from "./lightning-gun.interface";
import { MACHINEGUN_GRADE1 } from "./machinegun-grade-1.interface";
import { MACHINEGUN } from "./machinegun.interface";
import { NAILGUN_GRADE1 } from "./nailgun-grade-1.interface";
import { PLASMA_TRAIL } from "./plasma-trail.interface";
import { NAILGUN } from "./nailgun.interface";
import { RAILGUN } from "./railgun.interface";
import { ROCKET_LAUNCHER } from "./rocket-launcher.interface";
import { SHOTGUN_GRADE1 } from "./shotgun-grade-1.interface";
import { SHOTGUN } from "./shotgun.interface";
import { TELEFRAG } from "./telefrag.interface";
import { UNHOLY } from "./unholy.interface";
import { UNKNOWN_DAMAGE_TYPE } from "./unknown-damage-type.interface";
import { MINING_LASER } from "./mining-laser.interface";
import { AbilityBerserk } from "./ability-berserk.interface";
import { PLASMA_TRAIL_EXPLOSION } from "./plasma-trail-explosion.interface";
import { SWARM_GRENADE } from "./swarm-grenade.interface";
import { SB_DASH } from "./sb-dash.interface";
import { SB_STOMP } from "./sb-stomp.interface";
import { AcidSpitDirect } from "./acid-spit-direct.interface";
import { AcidDot } from "./acid-dot.interface";
import { VENDETTA_TELEFRAG } from "./vendetta-telefrag.interface";
import { FLAME_DOT } from "./flame-dot.interface";
import { FLAME } from "./flame.interface";
import { Acid } from "./acid.interface";
import { RECON_DRONE } from "./recon-drone.interface";
import { RECON_DRONE_EXPLOSION } from "./recon-drone-explosion.interface";
import { FLAME_MELEE } from "./flame-melee.interface";
import { TURRET } from "./turret.interface";
import { PUSH_TO_SUICIDE } from "./push-to-suicide.interface";
import { FLAME_DOMAIN } from "./flame-domain.interface";
import { DRONE_KAMIKAZE_EXPLOSION } from "./drone-kamikaze-explosion.interface";
import { ATHENA_HIT } from "./athena-hit.interface";

export interface DamageStatusList {
  UNKNOWN_DAMAGE_TYPE: UNKNOWN_DAMAGE_TYPE;
  GAUNTLET: GAUNTLET;
  MACHINEGUN: MACHINEGUN;
  MACHINEGUN_GRADE1: MACHINEGUN_GRADE1;
  SHOTGUN: SHOTGUN;
  SHOTGUN_GRADE1: SHOTGUN_GRADE1;
  NAILGUN: NAILGUN;
  NAILGUN_GRADE1: NAILGUN_GRADE1;
  ROCKET_LAUNCHER: ROCKET_LAUNCHER;
  LIGHTNING_GUN: LIGHTNING_GUN;
  RAILGUN: RAILGUN;
  LAGBOLT: LAGBOLT;
  ACID_DOMAIN: AcidDomain;
  DAMAGE_DOMAIN: DAMAGE_DOMAIN;
  KILL_DOMAIN: KILL_DOMAIN;
  DIRE_ORB: DIRE_ORB;
  DIRE_ORB_EXPLOSION: DIRE_ORB_EXPLOSION;
  DIRE_ORB_TELEFRAG: DIRE_ORB_TELEFRAG;
  UNHOLY: UNHOLY;
  TELEFRAG: TELEFRAG;
  FALL_DAMAGE: IFallDamage;
  PLASMA_TRAIL: PLASMA_TRAIL;
  PLASMA_TRAIL_EXPLOSION: PLASMA_TRAIL_EXPLOSION;
  MINING_LASER: MINING_LASER;
  ABILITY_BERSERK: AbilityBerserk;
  SWARM_GRENADE: SWARM_GRENADE;
  SB_DASH: SB_DASH;
  SB_STOMP: SB_STOMP;
  ACID_SPIT_DIRECT: AcidSpitDirect;
  VENDETTA_TELEFRAG: VENDETTA_TELEFRAG;
  ACID_DOT: AcidDot;
  FLAME_DOT: FLAME_DOT;
  FLAME: FLAME;
  ACID: Acid;
  DRONE_KAMIKAZE_EXPLOSION: DRONE_KAMIKAZE_EXPLOSION;
  RECON_DRONE: RECON_DRONE;
  RECON_DRONE_EXPLOSION: RECON_DRONE_EXPLOSION;
  ATHENA_HIT: ATHENA_HIT;
  FLAME_MELEE: FLAME_MELEE;
  FLAME_DOMAIN: FLAME_DOMAIN;
  TURRET: TURRET;
  PUSH_TO_SUICIDE: PUSH_TO_SUICIDE;
}
