import { ACID_DOMAIN } from "./a-c-i-d_-d-o-m-a-i.n.interface";
import { DAMAGE_DOMAIN } from "./d-a-m-a-g-e_-d-o-m-a-i.n.interface";
import { DIRE_ORB_EXPLOSION } from "./d-i-r-e_-o-r-b_-e-x-p-l-o-s-i-o.n.interface";
import { DIRE_ORB_TELEFRAG } from "./d-i-r-e_-o-r-b_-t-e-l-e-f-r-a.g.interface";
import { DIRE_ORB } from "./d-i-r-e_-o-r.b.interface";
import { FALL_DAMAGE } from "./f-a-l-l_-d-a-m-a-g.e.interface";
import { GAUNTLET } from "./g-a-u-n-t-l-e.t.interface";
import { KILL_DOMAIN } from "./k-i-l-l_-d-o-m-a-i.n.interface";
import { LAGBOLT } from "./l-a-g-b-o-l.t.interface";
import { LIGHTNING_GUN } from "./l-i-g-h-t-n-i-n-g_-g-u.n.interface";
import { MACHINEGUN_GRADE1 } from "./m-a-c-h-i-n-e-g-u-n_-g-r-a-d.e1.interface";
import { MACHINEGUN } from "./m-a-c-h-i-n-e-g-u.n.interface";
import { NAILGUN_GRADE1 } from "./n-a-i-l-g-u-n_-g-r-a-d.e1.interface";
import { PLASMA_TRAIL } from "./p-l-a-s-m-a_-t-r-a-i.l.interface";
import { NAILGUN } from "./n-a-i-l-g-u.n.interface";
import { RAILGUN } from "./r-a-i-l-g-u.n.interface";
import { ROCKET_LAUNCHER } from "./r-o-c-k-e-t_-l-a-u-n-c-h-e.r.interface";
import { SHOTGUN_GRADE1 } from "./s-h-o-t-g-u-n_-g-r-a-d.e1.interface";
import { SHOTGUN } from "./s-h-o-t-g-u.n.interface";
import { TELEFRAG } from "./t-e-l-e-f-r-a.g.interface";
import { UNHOLY } from "./u-n-h-o-l.y.interface";
import { UNKNOWN_DAMAGE_TYPE } from "./unknown-damage-type.interface";
import { MINING_LASER } from "./m-i-n-i-n-g_-l-a-s-e.r.interface";
import { ABILITY_BERSERK } from "./ability-berserk.interface";
import { PLASMA_TRAIL_EXPLOSION } from "./p-l-a-s-m-a_-t-r-a-i-l_-e-x-p-l-o-s-i-o.n.interface";
import { SWARM_GRENADE } from "./s-w-a-r-m_-g-r-e-n-a-d.e.interface";
import { SB_DASH } from "./s-b_-d-a-s.h.interface";
import { SB_STOMP } from "./s-b_-s-t-o-m.p.interface";
import { ACID_SPIT_DIRECT } from "./a-c-i-d_-s-p-i-t_-d-i-r-e-c.t.interface";
import { ACID_DOT } from "./acid-dot.interface";
import { VENDETTA_TELEFRAG } from "./v-e-n-d-e-t-t-a_-t-e-l-e-f-r-a.g.interface";
import { FLAME_DOT } from "./f-l-a-m-e_-d-o.t.interface";
import { FLAME } from "./f-l-a-m.e.interface";
import { ACID } from "./acid.interface";
import { RECON_DRONE } from "./r-e-c-o-n_-d-r-o-n.e.interface";
import { RECON_DRONE_EXPLOSION } from "./r-e-c-o-n_-d-r-o-n-e_-e-x-p-l-o-s-i-o.n.interface";
import { FLAME_MELEE } from "./f-l-a-m-e_-m-e-l-e.e.interface";
import { TURRET } from "./t-u-r-r-e.t.interface";
import { PUSH_TO_SUICIDE } from "./p-u-s-h_-t-o_-s-u-i-c-i-d.e.interface";
import { FLAME_DOMAIN } from "./f-l-a-m-e_-d-o-m-a-i.n.interface";
import { DRONE_KAMIKAZE_EXPLOSION } from "./d-r-o-n-e_-k-a-m-i-k-a-z-e_-e-x-p-l-o-s-i-o.n.interface";
import { ATHENA_HIT } from "./a-t-h-e-n-a_-h-i.t.interface";

export interface DamageStatusList {
  UNKNOWN_DAMAGE_TYPE: UNKNOWN_DAMAGE_TYPE;
  GAUNTLET: GAUNTLET;
  MACHINEGUN: MACHINEGUN;
  MACHINEGUN_GRADE1: MACHINEGUN_GRADE1;
  SHOTGUN: SHOTGUN;
  SHOTGUN_GRADE1: SHOTGUN_GRADE1;
  NAILGUN: NAILGUN;
  NAILGUN_GRADE1: NAILGUN_GRADE1;
  ROCKET_LAUNCHER: ROCKET_LAUNCHER;
  LIGHTNING_GUN: LIGHTNING_GUN;
  RAILGUN: RAILGUN;
  LAGBOLT: LAGBOLT;
  ACID_DOMAIN: ACID_DOMAIN;
  DAMAGE_DOMAIN: DAMAGE_DOMAIN;
  KILL_DOMAIN: KILL_DOMAIN;
  DIRE_ORB: DIRE_ORB;
  DIRE_ORB_EXPLOSION: DIRE_ORB_EXPLOSION;
  DIRE_ORB_TELEFRAG: DIRE_ORB_TELEFRAG;
  UNHOLY: UNHOLY;
  TELEFRAG: TELEFRAG;
  FALL_DAMAGE: FALL_DAMAGE;
  PLASMA_TRAIL: PLASMA_TRAIL;
  PLASMA_TRAIL_EXPLOSION: PLASMA_TRAIL_EXPLOSION;
  MINING_LASER: MINING_LASER;
  ABILITY_BERSERK: ABILITY_BERSERK;
  SWARM_GRENADE: SWARM_GRENADE;
  SB_DASH: SB_DASH;
  SB_STOMP: SB_STOMP;
  ACID_SPIT_DIRECT: ACID_SPIT_DIRECT;
  VENDETTA_TELEFRAG: VENDETTA_TELEFRAG;
  ACID_DOT: ACID_DOT;
  FLAME_DOT: FLAME_DOT;
  FLAME: FLAME;
  ACID: ACID;
  DRONE_KAMIKAZE_EXPLOSION: DRONE_KAMIKAZE_EXPLOSION;
  RECON_DRONE: RECON_DRONE;
  RECON_DRONE_EXPLOSION: RECON_DRONE_EXPLOSION;
  ATHENA_HIT: ATHENA_HIT;
  FLAME_MELEE: FLAME_MELEE;
  FLAME_DOMAIN: FLAME_DOMAIN;
  TURRET: TURRET;
  PUSH_TO_SUICIDE: PUSH_TO_SUICIDE;
}
